name: e2e Tests
on: [push, pull_request]
jobs:
  jest:
    name: e2e tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      
      - run: ./build-test.sh
        working-directory: ./tests/e2e

      - run: ./run-test.sh
        working-directory: ./tests/e2e

      - name: Check body is returned
        run: curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"path":"/hi"}' | jq -e 'has("body")'

      - name: Check binary file is handled correctly
        run: curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"path":"/rss.png"}' | jq -e '.headers["x-serverlesswp-binary"] == "true"'

      - name: Check preRequest plugin
        run: curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"path":"/index.php", "preRequestPlugin": "1"}' | jq -e '.body == "Foo"'

      - name: Check postRequest plugin
        run: curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"path":"/index.php", "postRequestPlugin": "1"}' | jq -e '.statusCode == 201'

      - run: docker stop serverlesswp-test; docker rm serverlesswp-test

      - run: ./run-test.sh
        working-directory: ./tests/e2e
        env:
          HOST: "Vercel"

      - name: Check if Vercel cookies are correct
        run: curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"path":"/hi"}' | jq -e 'if (.headers["set-cookie"] | length == 2) then true else false end'

      - run:  docker stop serverlesswp-test; docker rm serverlesswp-test

      - run: ./run-test.sh
        working-directory: ./tests/e2e
        env:
          HOST: "Netlify"

      - name: Check if Netlify cookies are correct
        run: curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"path":"/hi"}' | jq -e 'if (.multiValueHeaders["set-cookie"] | length == 2) then true else false end'

      - run:  docker stop serverlesswp-test; docker rm serverlesswp-test

      - run: ./run-test.sh
        working-directory: ./tests/e2e
        env:
          HOST: "AWS"

      - name: Check if AWS cookies are correct
        run: curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"path":"/hi"}' | jq -e 'if (.cookies | length == 2) then true else false end'