name: e2e Tests
on: [push, pull_request]
jobs:
  jest:
    name: e2e tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      
      - run: ./build-test.sh
        working-directory: ./tests/e2e

      - run: ./run-test.sh
        working-directory: ./tests/e2e

      - run: curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"path":"/hi"}'