name: Jest Tests
on: [push, pull_request]
jobs:
  jest:
    name: Jest tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - run: npm ci

      - run: npm run test